/**
 * @file constants/mockData.ts
 * Seed data for mock services. Replace with real API calls when backend is ready.
 * Cameras represent forward-facing IR/thermal units on harvesting equipment.
 * Alerts represent historical wildlife detections from the YOLO edge model.
 */

import type { Alert, Camera } from '@/types';

// ─────────────────────────────────────────────
// Mock Cameras — 4 IR Units on the Harvester
// ─────────────────────────────────────────────

export const MOCK_CAMERAS: Camera[] = [
  {
    id: 'cam-001',
    name: 'Front Left IR',
    type: 'WiFi',
    streamUrl: 'rtsp://192.168.1.101:554/stream1',
    ipAddress: '192.168.1.101',
    port: 554,
    fieldLocation: 'Field A — North Quadrant',
    cropDensity: 'Heavy',
    status: 'online',
    latencyMs: 42,
    lastSeenAt: new Date(Date.now() - 3000).toISOString(),
  },
  {
    id: 'cam-002',
    name: 'Front Right IR',
    type: 'WiFi',
    streamUrl: 'rtsp://192.168.1.102:554/stream1',
    ipAddress: '192.168.1.102',
    port: 554,
    fieldLocation: 'Field A — North Quadrant',
    cropDensity: 'Heavy',
    status: 'online',
    latencyMs: 58,
    lastSeenAt: new Date(Date.now() - 1500).toISOString(),
  },
  {
    id: 'cam-003',
    name: 'Rear Centre IR',
    type: 'LAN',
    streamUrl: 'rtsp://10.0.0.50:8554/live',
    ipAddress: '10.0.0.50',
    port: 8554,
    fieldLocation: 'Field B — East Row',
    cropDensity: 'Medium',
    status: 'online',
    latencyMs: 31,
    lastSeenAt: new Date(Date.now() - 800).toISOString(),
  },
  {
    id: 'cam-004',
    name: 'Side Flank IR',
    type: 'RTSP',
    streamUrl: 'rtsp://10.0.0.51:8554/thermal',
    ipAddress: '10.0.0.51',
    port: 8554,
    fieldLocation: 'Field B — West Row',
    cropDensity: 'Light',
    status: 'offline',
    latencyMs: 0,
    lastSeenAt: new Date(Date.now() - 120000).toISOString(),
  },
];

// ─────────────────────────────────────────────
// Mock Alerts — 12 historical detection events
// ─────────────────────────────────────────────

const now = Date.now();
const mins = (n: number) => n * 60 * 1000;
const hours = (n: number) => n * 60 * mins(1);

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    cameraId: 'cam-001',
    cameraName: 'Front Left IR',
    timestamp: new Date(now - mins(4)).toISOString(),
    animalType: 'Nilgai',
    confidenceScore: 0.942,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-001',
    boundingBox: { x: 0.35, y: 0.2, width: 0.28, height: 0.45 },
    status: 'active',
    severity: 'critical',
  },
  {
    id: 'alert-002',
    cameraId: 'cam-002',
    cameraName: 'Front Right IR',
    timestamp: new Date(now - mins(18)).toISOString(),
    animalType: 'Fawn',
    confidenceScore: 0.874,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-002',
    boundingBox: { x: 0.55, y: 0.3, width: 0.18, height: 0.32 },
    status: 'acknowledged',
    severity: 'critical',
    resolutionNote: 'Operator slowed harvester. Fawn moved to field edge.',
  },
  {
    id: 'alert-003',
    cameraId: 'cam-003',
    cameraName: 'Rear Centre IR',
    timestamp: new Date(now - mins(45)).toISOString(),
    animalType: 'Wild Boar',
    confidenceScore: 0.789,
    cropDensity: 'Medium',
    snapshotUri: 'mock://snapshot/alert-003',
    boundingBox: { x: 0.2, y: 0.4, width: 0.35, height: 0.38 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Harvester stopped. Animal cleared.',
  },
  {
    id: 'alert-004',
    cameraId: 'cam-001',
    cameraName: 'Front Left IR',
    timestamp: new Date(now - hours(2)).toISOString(),
    animalType: 'Rabbit',
    confidenceScore: 0.651,
    cropDensity: 'Medium',
    snapshotUri: 'mock://snapshot/alert-004',
    boundingBox: { x: 0.6, y: 0.5, width: 0.12, height: 0.15 },
    status: 'resolved',
    severity: 'warning',
    resolutionNote: 'False alarm confirmed after second pass.',
  },
  {
    id: 'alert-005',
    cameraId: 'cam-003',
    cameraName: 'Rear Centre IR',
    timestamp: new Date(now - hours(3)).toISOString(),
    animalType: 'Nilgai',
    confidenceScore: 0.918,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-005',
    boundingBox: { x: 0.28, y: 0.15, width: 0.32, height: 0.5 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Emergency stop triggered. Animal evaded.',
  },
  {
    id: 'alert-006',
    cameraId: 'cam-002',
    cameraName: 'Front Right IR',
    timestamp: new Date(now - hours(5)).toISOString(),
    animalType: 'Fox',
    confidenceScore: 0.713,
    cropDensity: 'Light',
    snapshotUri: 'mock://snapshot/alert-006',
    boundingBox: { x: 0.45, y: 0.35, width: 0.2, height: 0.25 },
    status: 'resolved',
    severity: 'warning',
    resolutionNote: 'Dismissed — fox moved before harvester reached.',
  },
  {
    id: 'alert-007',
    cameraId: 'cam-001',
    cameraName: 'Front Left IR',
    timestamp: new Date(now - hours(8)).toISOString(),
    animalType: 'Fawn',
    confidenceScore: 0.962,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-007',
    boundingBox: { x: 0.38, y: 0.22, width: 0.22, height: 0.38 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Emergency stop. Fawn carried to field edge by operator.',
  },
  {
    id: 'alert-008',
    cameraId: 'cam-003',
    cameraName: 'Rear Centre IR',
    timestamp: new Date(now - hours(12)).toISOString(),
    animalType: 'Unknown',
    confidenceScore: 0.502,
    cropDensity: 'Medium',
    snapshotUri: 'mock://snapshot/alert-008',
    boundingBox: { x: 0.5, y: 0.4, width: 0.15, height: 0.2 },
    status: 'resolved',
    severity: 'info',
    resolutionNote: 'Unidentified. Likely debris. Dismissed.',
  },
  {
    id: 'alert-009',
    cameraId: 'cam-002',
    cameraName: 'Front Right IR',
    timestamp: new Date(now - hours(16)).toISOString(),
    animalType: 'Wild Boar',
    confidenceScore: 0.881,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-009',
    boundingBox: { x: 0.22, y: 0.28, width: 0.4, height: 0.42 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Harvester detoured. Boar cleared.',
  },
  {
    id: 'alert-010',
    cameraId: 'cam-001',
    cameraName: 'Front Left IR',
    timestamp: new Date(now - hours(20)).toISOString(),
    animalType: 'Nilgai',
    confidenceScore: 0.835,
    cropDensity: 'Medium',
    snapshotUri: 'mock://snapshot/alert-010',
    boundingBox: { x: 0.3, y: 0.18, width: 0.3, height: 0.48 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Resolved — slow approach, animal left field.',
  },
  {
    id: 'alert-011',
    cameraId: 'cam-003',
    cameraName: 'Rear Centre IR',
    timestamp: new Date(now - hours(24)).toISOString(),
    animalType: 'Rabbit',
    confidenceScore: 0.612,
    cropDensity: 'Light',
    snapshotUri: 'mock://snapshot/alert-011',
    boundingBox: { x: 0.65, y: 0.55, width: 0.1, height: 0.12 },
    status: 'resolved',
    severity: 'warning',
    resolutionNote: 'Dismissed as false alarm.',
  },
  {
    id: 'alert-012',
    cameraId: 'cam-002',
    cameraName: 'Front Right IR',
    timestamp: new Date(now - hours(28)).toISOString(),
    animalType: 'Fawn',
    confidenceScore: 0.945,
    cropDensity: 'Heavy',
    snapshotUri: 'mock://snapshot/alert-012',
    boundingBox: { x: 0.4, y: 0.25, width: 0.25, height: 0.4 },
    status: 'resolved',
    severity: 'critical',
    resolutionNote: 'Emergency stop. Fawn relocated.',
  },
];
